### ISSUE TITLE
MNN aarch64 环境编译出错错误

### ISSUE THREAD

**Issue by iftaken** [alibaba/MNN#1310]
# 平台(如果交叉编译请再附上交叉编译目标平台):  
# Platform(Include target platform as well if cross-compiling):  
Linux ecs-yizhi-waihu-freeswitch01 4.18.0-147.0.3.el7.aarch64 #1 SMP Thu Dec 12 20:01:00 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux

# Github版本:
# Github Version: b0dbe49776772d3cba95402a2c9f2f5d9216f6b7

# 编译方式:
# Compiling Method

```
cd /path/to/MNN
./schema/generate.sh
mkdir build && cd build && cmake .. && make -j4
```

# 编译日志:
# Build Log:
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/gcc
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python (found version "2.7.5") 
-- >>>>>>>>>>>>>
-- MNN BUILD INFO:
-- 	System: Linux
-- 	Processor: aarch64
-- 	Metal: OFF
-- 	OpenCL: OFF
-- 	OpenGL: OFF
-- 	Vulkan: OFF
-- 	ARM82: OFF
-- 	TensorRT: OFF
-- 	CUDA: OFF
-- 	OpenMP: OFF
-- 	Hidden: TRUE
-- 	Build Path: /root/Project-hym/mnn/build
-- Enabling AArch64 Assemblies
-- Configuring done
-- Generating done
-- Build files have been written to:
```
mnn/source/backend/cpu/arm/arm64/MNNVectorTop1Float.S: Assembler messages:
mnn/source/backend/cpu/arm/arm64/MNNVectorTop1Float.S:35: Error: operand mismatch -- `mov v28.4s,v29.4s'
mnn/source/backend/cpu/arm/arm64/MNNVectorTop1Float.S:35: Info:    did you mean this?
mnn/source/backend/cpu/arm/arm64/MNNVectorTop1Float.S:35: Info:    	mov v28.8b,v29.8b
mnn/source/backend/cpu/arm/arm64/MNNVectorTop1Float.S:35: Info:    other valid variant(s):
mnn/source/backend/cpu/arm/arm64/MNNVectorTop1Float.S:35: Info:    	mov v28.16b,v29.16b
make[2]: *** [CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNVectorTop1Float.S.o] Error 1
make[1]: *** [CMakeFiles/MNNARM64.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

```

**Comment by joaoz** [comment]
I'm having the same error trying to compile on a jetson nano 4.9.140-tegra #1 SMP PREEMPT Fri Oct 16 12:32:46 PDT 2020 aarch64 aarch64 aarch64 GNU/Linux

**Comment by joaoz** [comment]
I managed to build using version: 6b0c16f24f222239ecce8fb61c51b7f267502670

**Comment by iftaken** [comment]
> I managed to build using version: [6b0c16f](https://github.com/alibaba/MNN/commit/6b0c16f24f222239ecce8fb61c51b7f267502670)

Thank you very much! I success too !

**Comment by iftaken** [comment]
But I meet new error!
`
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNAddBias.S.o: In function `MNNAddBias':
(.text+0x0): multiple definition of `MNNAddBias'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/CommonOptFunction.cpp.o:CommonOptFunction.cpp:(.text.MNNAddBias+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNAddBiasRelu.S.o: In function `MNNAddBiasRelu':
(.text+0x0): multiple definition of `MNNAddBiasRelu'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/CommonOptFunction.cpp.o:CommonOptFunction.cpp:(.text.MNNAddBiasRelu+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNAddBiasRelu6.S.o: In function `MNNAddBiasRelu6':
(.text+0x0): multiple definition of `MNNAddBiasRelu6'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/CommonOptFunction.cpp.o:CommonOptFunction.cpp:(.text.MNNAddBiasRelu6+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNAddC4WithStride.S.o: In function `MNNAddC4WithStride':
(.text+0x0): multiple definition of `MNNAddC4WithStride'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/CommonOptFunction.cpp.o:CommonOptFunction.cpp:(.text.MNNAddC4WithStride+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNAxByClampBroadcastC4.S.o: In function `MNNAxByClampBroadcastC4':
(.text+0x0): multiple definition of `MNNAxByClampBroadcastC4'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/CommonOptFunction.cpp.o:CommonOptFunction.cpp:(.text.MNNAxByClampBroadcastC4+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNConvDwF23MulTransUnit.S.o: In function `MNNConvDwF23MulTransUnit':
(.text+0x0): multiple definition of `MNNConvDwF23MulTransUnit'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/ConvolutionDepthwise3x3.cpp.o:ConvolutionDepthwise3x3.cpp:(.text.MNNConvDwF23MulTransUnit+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNConvDwF23SourceTransUnit.S.o: In function `MNNConvDwF23SourceTransUnit':
(.text+0x0): multiple definition of `MNNConvDwF23SourceTransUnit'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/ConvolutionDepthwise3x3.cpp.o:ConvolutionDepthwise3x3.cpp:(.text.MNNConvDwF23SourceTransUnit+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNConvRunForLineDepthWiseInt8.S.o: In function `MNNConvRunForLineDepthWiseInt8':
(.text+0x0): multiple definition of `MNNConvRunForLineDepthWiseInt8'
CMakeFiles/MNNCPU.dir/source/backend/cpu/CPUConvolutionDepthwise.cpp.o:CPUConvolutionDepthwise.cpp:(.text.MNNConvRunForLineDepthWiseInt8+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNConvRunForLineDepthWiseUint8.S.o: In function `MNNConvRunForLineDepthWiseUint8':
(.text+0x0): multiple definition of `MNNConvRunForLineDepthWiseUint8'
CMakeFiles/MNNCPU.dir/source/backend/cpu/CPUQuanConvolutionDepthwise.cpp.o:CPUQuanConvolutionDepthwise.cpp:(.text.MNNConvRunForLineDepthWiseUint8+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNConvRunForLineDepthwise.S.o: In function `MNNConvRunForLineDepthwise':
(.text+0x0): multiple definition of `MNNConvRunForLineDepthwise'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/ConvOpt.cpp.o:ConvOpt.cpp:(.text.MNNConvRunForLineDepthwise+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNConvRunForUnitDepthWise.S.o: In function `MNNConvRunForUnitDepthWise':
(.text+0x0): multiple definition of `MNNConvRunForUnitDepthWise'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/ConvOpt.cpp.o:ConvOpt.cpp:(.text.MNNConvRunForUnitDepthWise+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNConvRunForUnitDepthWiseInt8.S.o: In function `MNNConvRunForUnitDepthWiseInt8':
(.text+0x0): multiple definition of `MNNConvRunForUnitDepthWiseInt8'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/Int8FunctionsOpt.cpp.o:Int8FunctionsOpt.cpp:(.text.MNNConvRunForUnitDepthWiseInt8+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNConvRunForUnitDepthWiseUint8.S.o: In function `MNNConvRunForUnitDepthWiseUint8':
(.text+0x0): multiple definition of `MNNConvRunForUnitDepthWiseUint8'
CMakeFiles/MNNCPU.dir/source/backend/cpu/CPUQuanConvolutionDepthwise.cpp.o:CPUQuanConvolutionDepthwise.cpp:(.text.MNNConvRunForUnitDepthWiseUint8+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNCopyC4WithStride.S.o: In function `MNNCopyC4WithStride':
(.text+0x0): multiple definition of `MNNCopyC4WithStride'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/CommonOptFunction.cpp.o:CommonOptFunction.cpp:(.text.MNNCopyC4WithStride+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNDeconvRunForUnitDepthWise.S.o: In function `MNNDeconvRunForUnitDepthWise':
(.text+0x0): multiple definition of `MNNDeconvRunForUnitDepthWise'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/ConvOpt.cpp.o:ConvOpt.cpp:(.text.MNNDeconvRunForUnitDepthWise+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNExpC8.S.o: In function `MNNExpC8':
(.text+0x0): multiple definition of `MNNExpC8'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/CommonOptFunction.cpp.o:CommonOptFunction.cpp:(.text.MNNExpC8+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNFloat2Int8.S.o: In function `MNNFloat2Int8':
(.text+0x0): multiple definition of `MNNFloat2Int8'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/Int8FunctionsOpt.cpp.o:Int8FunctionsOpt.cpp:(.text.MNNFloat2Int8+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNGemmFloatCommon_4.S.o: In function `MNNGemmFloatCommon_4':
(.text+0x0): multiple definition of `MNNGemmFloatCommon_4'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/ConvOpt.cpp.o:ConvOpt.cpp:(.text.MNNGemmFloatCommon_4+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNGemmFloatOne_4.S.o: In function `MNNGemmFloatOne_4':
(.text+0x0): multiple definition of `MNNGemmFloatOne_4'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/ConvOpt.cpp.o:ConvOpt.cpp:(.text.MNNGemmFloatOne_4+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNGemmFloatUnit_4.S.o: In function `MNNGemmFloatUnit_4':
(.text+0x0): multiple definition of `MNNGemmFloatUnit_4'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/ConvOpt.cpp.o:ConvOpt.cpp:(.text.MNNGemmFloatUnit_4+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_16x4_Unit.S.o: In function `MNNGemmInt8AddBiasScale_16x4_Unit':
(.text+0x0): multiple definition of `MNNGemmInt8AddBiasScale_16x4_Unit'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/Int8FunctionsOpt.cpp.o:Int8FunctionsOpt.cpp:(.text.MNNGemmInt8AddBiasScale_16x4_Unit+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNGemmInt8AddBiasScale_16x4_Unit_FAST.S.o: In function `MNNGemmInt8AddBiasScale_16x4_Unit_FAST':
(.text+0x0): multiple definition of `MNNGemmInt8AddBiasScale_16x4_Unit_FAST'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/Int8FunctionsOpt.cpp.o:Int8FunctionsOpt.cpp:(.text.MNNGemmInt8AddBiasScale_16x4_Unit_FAST+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNGemmInt8toFloat32_8x4_Common.S.o: In function `MNNGemmInt8toFloat32_8x4_Common':
(.text+0x0): multiple definition of `MNNGemmInt8toFloat32_8x4_Common'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/Int8FunctionsOpt.cpp.o:Int8FunctionsOpt.cpp:(.text.MNNGemmInt8toFloat32_8x4_Common+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNGemmInt8toFloat32_8x4_Unit.S.o: In function `MNNGemmInt8toFloat32_8x4_Unit':
(.text+0x0): multiple definition of `MNNGemmInt8toFloat32_8x4_Unit'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/Int8FunctionsOpt.cpp.o:Int8FunctionsOpt.cpp:(.text.MNNGemmInt8toFloat32_8x4_Unit+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNGemmint8to32_8x4_Unit.S.o: In function `MNNGemmint8to32_8x4_Unit':
(.text+0x0): multiple definition of `MNNGemmint8to32_8x4_Unit'
CMakeFiles/MNNCPU.dir/source/backend/cpu/CPUTFQuantizedConv2D.cpp.o:CPUTFQuantizedConv2D.cpp:(.text.MNNGemmint8to32_8x4_Unit+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNLoadU8AndSum.S.o: In function `MNNLoadU8AndSum':
(.text+0x0): multiple definition of `MNNLoadU8AndSum'
CMakeFiles/MNNCPU.dir/source/backend/cpu/CPUTFQuantizedConv2D.cpp.o:CPUTFQuantizedConv2D.cpp:(.text.MNNLoadU8AndSum+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNMatrixAdd.S.o: In function `MNNMatrixAdd':
(.text+0x0): multiple definition of `MNNMatrixAdd'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/ConvOpt.cpp.o:ConvOpt.cpp:(.text.MNNMatrixAdd+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNMatrixMax.S.o: In function `MNNMatrixMax':
(.text+0x0): multiple definition of `MNNMatrixMax'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/ConvOpt.cpp.o:ConvOpt.cpp:(.text.MNNMatrixMax+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNMatrixProd.S.o: In function `MNNMatrixProd':
(.text+0x0): multiple definition of `MNNMatrixProd'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/ConvOpt.cpp.o:ConvOpt.cpp:(.text.MNNMatrixProd+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNMatrixSub.S.o: In function `MNNMatrixSub':
(.text+0x0): multiple definition of `MNNMatrixSub'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/ConvOpt.cpp.o:ConvOpt.cpp:(.text.MNNMatrixSub+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNMaxFloat.S.o: In function `MNNMaxFloat':
(.text+0x0): multiple definition of `MNNMaxFloat'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/CommonOptFunction.cpp.o:CommonOptFunction.cpp:(.text.MNNMaxFloat+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNMinFloat.S.o: In function `MNNMinFloat':
(.text+0x0): multiple definition of `MNNMinFloat'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/CommonOptFunction.cpp.o:CommonOptFunction.cpp:(.text.MNNMinFloat+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNPackC4.S.o: In function `MNNPackC4':
(.text+0x0): multiple definition of `MNNPackC4'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/CommonOptFunction.cpp.o:CommonOptFunction.cpp:(.text.MNNPackC4+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNPackC4ForMatMul_A.S.o: In function `MNNPackC4ForMatMul_A':
(.text+0x0): multiple definition of `MNNPackC4ForMatMul_A'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/CommonOptFunction.cpp.o:CommonOptFunction.cpp:(.text.MNNPackC4ForMatMul_A+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNPackedMatMul.S.o: In function `MNNPackedMatMul':
(.text+0x0): multiple definition of `MNNPackedMatMul'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/CommonOptFunction.cpp.o:CommonOptFunction.cpp:(.text.MNNPackedMatMul+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNPackedMatMulRemain.S.o: In function `MNNPackedMatMulRemain':
(.text+0x0): multiple definition of `MNNPackedMatMulRemain'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/CommonOptFunction.cpp.o:CommonOptFunction.cpp:(.text.MNNPackedMatMulRemain+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNPowC8.S.o: In function `MNNPowC8':
(.text+0x0): multiple definition of `MNNPowC8'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/CommonOptFunction.cpp.o:CommonOptFunction.cpp:(.text.MNNPowC8+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNQuanToDestUint8.S.o: In function `MNNQuanToDestUint8':
(.text+0x0): multiple definition of `MNNQuanToDestUint8'
CMakeFiles/MNNCPU.dir/source/backend/cpu/CPUTFQuantizedConv2D.cpp.o:CPUTFQuantizedConv2D.cpp:(.text.MNNQuanToDestUint8+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNReluInt8.S.o: In function `MNNReluInt8':
(.text+0x0): multiple definition of `MNNReluInt8'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/CommonOptFunction.cpp.o:CommonOptFunction.cpp:(.text.MNNReluInt8+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNReluWithSlopeChannel.S.o: In function `MNNReluWithSlopeChannel':
(.text+0x0): multiple definition of `MNNReluWithSlopeChannel'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/CommonOptFunction.cpp.o:CommonOptFunction.cpp:(.text.MNNReluWithSlopeChannel+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNScaleAndAddBias.S.o: In function `MNNScaleAndAddBias':
(.text+0x0): multiple definition of `MNNScaleAndAddBias'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/CommonOptFunction.cpp.o:CommonOptFunction.cpp:(.text.MNNScaleAndAddBias+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNStrassenMergeCFunction.S.o: In function `MNNStrassenMergeCFunction':
(.text+0x0): multiple definition of `MNNStrassenMergeCFunction'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/StrassenMatmulComputor.cpp.o:StrassenMatmulComputor.cpp:(.text.MNNStrassenMergeCFunction+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNUInt8ToInt16WithOffsetC4Common.S.o: In function `MNNUInt8ToInt16WithOffsetC4Common':
(.text+0x0): multiple definition of `MNNUInt8ToInt16WithOffsetC4Common'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/CommonOptFunction.cpp.o:CommonOptFunction.cpp:(.text.MNNUInt8ToInt16WithOffsetC4Common+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNUInt8ToInt16WithOffsetC4Fast.S.o: In function `MNNUInt8ToInt16WithOffsetC4Fast':
(.text+0x0): multiple definition of `MNNUInt8ToInt16WithOffsetC4Fast'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/CommonOptFunction.cpp.o:CommonOptFunction.cpp:(.text.MNNUInt8ToInt16WithOffsetC4Fast+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNUnPackC4.S.o: In function `MNNUnpackC4':
(.text+0x0): multiple definition of `MNNUnpackC4'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/CommonOptFunction.cpp.o:CommonOptFunction.cpp:(.text.MNNUnpackC4+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNWinogradMatrixProductLeft.S.o: In function `MNNWinogradMatrixProductLeft':
(.text+0x0): multiple definition of `MNNWinogradMatrixProductLeft'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/WinogradOptFunction.cpp.o:WinogradOptFunction.cpp:(.text.MNNWinogradMatrixProductLeft+0x0): first defined here
CMakeFiles/MNNARM64.dir/source/backend/cpu/arm/arm64/MNNWinogradMatrixProductRight.S.o: In function `MNNWinogradMatrixProductRight':
(.text+0x0): multiple definition of `MNNWinogradMatrixProductRight'
CMakeFiles/MNNCompute.dir/source/backend/cpu/compute/WinogradOptFunction.cpp.o:WinogradOptFunction.cpp:(.text.MNNWinogradMatrixProductRight+0x0): first defined here
`

**Comment by joaoz** [comment]
Try to build with this version d4316ada8f9da9f6bf3cb28df132c41cf58c971d

**Comment by MichaelXin** [comment]
I meet the same error. Have you solved this problem yet? @iftaken

**Comment by yyfcc17** [comment]
change line 'mov v28.4s,v29.4s' to 'mov v28.16b,v29.16b', will solve this problem
